# Generated by Django 5.2 on 2025-04-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='scent',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
