# Generated by Django 5.2 on 2025-04-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image_product_scent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='scent',
        ),
        migrations.AddField(
            model_name='product',
            name='aroma',
            field=models.CharField(default='Unscented', max_length=200),
        ),
    ]
